/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Attack
 */
export interface Attack {
    /**
     * 
     * @type {number}
     * @memberof Attack
     */
    numRolls: number;
    /**
     * 
     * @type {number}
     * @memberof Attack
     */
    modifier: number;
}

export function AttackFromJSON(json: any): Attack {
    return AttackFromJSONTyped(json, false);
}

export function AttackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numRolls': json['num_rolls'],
        'modifier': json['modifier'],
    };
}

export function AttackToJSON(value?: Attack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'num_rolls': value.numRolls,
        'modifier': value.modifier,
    };
}

