/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Effects,
    EffectsFromJSON,
    EffectsFromJSONTyped,
    EffectsToJSON,
} from './Effects';
import {
    Inventory,
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
} from './Inventory';
import {
    LifeModifier,
    LifeModifierFromJSON,
    LifeModifierFromJSONTyped,
    LifeModifierToJSON,
} from './LifeModifier';
import {
    Species,
    SpeciesFromJSON,
    SpeciesFromJSONTyped,
    SpeciesToJSON,
} from './Species';
import {
    SpellMemory,
    SpellMemoryFromJSON,
    SpellMemoryFromJSONTyped,
    SpellMemoryToJSON,
} from './SpellMemory';
import {
    Stats,
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
} from './Stats';

/**
 * 
 * @export
 * @interface Character
 */
export interface Character {
    /**
     * 
     * @type {Stats}
     * @memberof Character
     */
    stats: Stats;
    /**
     * 
     * @type {Species}
     * @memberof Character
     */
    species: Species;
    /**
     * 
     * @type {LifeModifier}
     * @memberof Character
     */
    life_modifier?: LifeModifier;
    /**
     * 
     * @type {Inventory}
     * @memberof Character
     */
    inventory?: Inventory;
    /**
     * 
     * @type {boolean}
     * @memberof Character
     */
    inventory_known: boolean;
    /**
     * 
     * @type {Effects}
     * @memberof Character
     */
    current_effects?: Effects;
    /**
     * 
     * @type {boolean}
     * @memberof Character
     */
    current_effects_known: boolean;
    /**
     * 
     * @type {SpellMemory}
     * @memberof Character
     */
    spell_memory?: SpellMemory;
    /**
     * 
     * @type {boolean}
     * @memberof Character
     */
    spell_memory_known: boolean;
}

export function CharacterFromJSON(json: any): Character {
    return CharacterFromJSONTyped(json, false);
}

export function CharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Character {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': StatsFromJSON(json['stats']),
        'species': SpeciesFromJSON(json['species']),
        'life_modifier': !exists(json, 'life_modifier') ? undefined : LifeModifierFromJSON(json['life_modifier']),
        'inventory': !exists(json, 'inventory') ? undefined : InventoryFromJSON(json['inventory']),
        'inventory_known': json['inventory_known'],
        'current_effects': !exists(json, 'current_effects') ? undefined : EffectsFromJSON(json['current_effects']),
        'current_effects_known': json['current_effects_known'],
        'spell_memory': !exists(json, 'spell_memory') ? undefined : SpellMemoryFromJSON(json['spell_memory']),
        'spell_memory_known': json['spell_memory_known'],
    };
}

export function CharacterToJSON(value?: Character | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': StatsToJSON(value.stats),
        'species': SpeciesToJSON(value.species),
        'life_modifier': LifeModifierToJSON(value.life_modifier),
        'inventory': InventoryToJSON(value.inventory),
        'inventory_known': value.inventory_known,
        'current_effects': EffectsToJSON(value.current_effects),
        'current_effects_known': value.current_effects_known,
        'spell_memory': SpellMemoryToJSON(value.spell_memory),
        'spell_memory_known': value.spell_memory_known,
    };
}

