/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EquipLocationTag,
    EquipLocationTagFromJSON,
    EquipLocationTagFromJSONTyped,
    EquipLocationTagToJSON,
} from './EquipLocationTag';
import {
    Item,
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface CharacterItem
 */
export interface CharacterItem {
    /**
     * 
     * @type {Item}
     * @memberof CharacterItem
     */
    item: Item;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterItem
     */
    isHidden?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterItem
     */
    knowsEquippedLocation: boolean;
    /**
     * 
     * @type {EquipLocationTag}
     * @memberof CharacterItem
     */
    equippedLocation?: EquipLocationTag;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterItem
     */
    isMultiple: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterItem
     */
    atTheReady: boolean;
}

export function CharacterItemFromJSON(json: any): CharacterItem {
    return CharacterItemFromJSONTyped(json, false);
}

export function CharacterItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': ItemFromJSON(json['item']),
        'isHidden': !exists(json, 'is_hidden') ? undefined : json['is_hidden'],
        'knowsEquippedLocation': json['knows_equipped_location'],
        'equippedLocation': !exists(json, 'equipped_location') ? undefined : EquipLocationTagFromJSON(json['equipped_location']),
        'isMultiple': json['is_multiple'],
        'atTheReady': json['at_the_ready'],
    };
}

export function CharacterItemToJSON(value?: CharacterItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': ItemToJSON(value.item),
        'is_hidden': value.isHidden,
        'knows_equipped_location': value.knowsEquippedLocation,
        'equipped_location': EquipLocationTagToJSON(value.equippedLocation),
        'is_multiple': value.isMultiple,
        'at_the_ready': value.atTheReady,
    };
}

