/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ConsumableEffectName = {
    LearnSpell: 'learn_spell',
    HealingGrog: 'healing_grog'
} as const;
export type ConsumableEffectName = typeof ConsumableEffectName[keyof typeof ConsumableEffectName];


export function ConsumableEffectNameFromJSON(json: any): ConsumableEffectName {
    return ConsumableEffectNameFromJSONTyped(json, false);
}

export function ConsumableEffectNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumableEffectName {
    return json as ConsumableEffectName;
}

export function ConsumableEffectNameToJSON(value?: ConsumableEffectName | null): any {
    return value as any;
}

