/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FixtureType = {
    Barrel: 'barrel',
    Bed: 'bed',
    Bucket: 'bucket',
    Chair: 'chair',
    Chest: 'chest',
    Coffin: 'coffin',
    Cot: 'cot',
    Crate: 'crate',
    Pillar: 'pillar',
    SleepingRoll: 'sleeping_roll',
    StatueTentacledMonstrosity: 'statue_tentacled_monstrosity',
    StatueWarrior: 'statue_warrior',
    Table: 'table',
    WeaponRack: 'weapon_rack'
} as const;
export type FixtureType = typeof FixtureType[keyof typeof FixtureType];


export function FixtureTypeFromJSON(json: any): FixtureType {
    return FixtureTypeFromJSONTyped(json, false);
}

export function FixtureTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureType {
    return json as FixtureType;
}

export function FixtureTypeToJSON(value?: FixtureType | null): any {
    return value as any;
}

