/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ItemDescriptor = {
    Beaten: 'beaten',
    Bleached: 'bleached',
    Bloodstained: 'bloodstained',
    Broken: 'broken',
    Chipped: 'chipped',
    Colourful: 'colourful',
    Cracked: 'cracked',
    Crumbling: 'crumbling',
    Dingy: 'dingy',
    Dirty: 'dirty',
    Drab: 'drab',
    Dull: 'dull',
    IllFitting: 'ill_fitting',
    LooseFitting: 'loose_fitting',
    Ripped: 'ripped',
    Rotting: 'rotting',
    Rusty: 'rusty',
    Scuffed: 'scuffed',
    SetOf: 'set_of',
    Shimmering: 'shimmering',
    Shiny: 'shiny',
    Smoothed: 'smoothed',
    Splintered: 'splintered',
    Stained: 'stained',
    Tangled: 'tangled',
    Tarnished: 'tarnished',
    Torn: 'torn',
    WaterLogged: 'water_logged',
    Weathered: 'weathered'
} as const;
export type ItemDescriptor = typeof ItemDescriptor[keyof typeof ItemDescriptor];


export function ItemDescriptorFromJSON(json: any): ItemDescriptor {
    return ItemDescriptorFromJSONTyped(json, false);
}

export function ItemDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemDescriptor {
    return json as ItemDescriptor;
}

export function ItemDescriptorToJSON(value?: ItemDescriptor | null): any {
    return value as any;
}

