/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Spell,
    SpellFromJSON,
    SpellFromJSONTyped,
    SpellToJSON,
} from './Spell';

/**
 * 
 * @export
 * @interface LearnedSpell
 */
export interface LearnedSpell {
    /**
     * 
     * @type {string}
     * @memberof LearnedSpell
     */
    id: string;
    /**
     * 
     * @type {Spell}
     * @memberof LearnedSpell
     */
    spell: Spell;
    /**
     * 
     * @type {string}
     * @memberof LearnedSpell
     */
    learned_at: string;
}

export function LearnedSpellFromJSON(json: any): LearnedSpell {
    return LearnedSpellFromJSONTyped(json, false);
}

export function LearnedSpellFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearnedSpell {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'spell': SpellFromJSON(json['spell']),
        'learned_at': json['learned_at'],
    };
}

export function LearnedSpellToJSON(value?: LearnedSpell | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'spell': SpellToJSON(value.spell),
        'learned_at': value.learned_at,
    };
}

