/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Material = {
    Bone: 'bone',
    Cotton: 'cotton',
    Fur: 'fur',
    Gold: 'gold',
    Hide: 'hide',
    Iron: 'iron',
    Leather: 'leather',
    Linen: 'linen',
    Paper: 'paper',
    Papyrus: 'papyrus',
    Silk: 'silk',
    Steel: 'steel',
    Stone: 'stone',
    Wooden: 'wooden',
    Wool: 'wool'
} as const;
export type Material = typeof Material[keyof typeof Material];


export function MaterialFromJSON(json: any): Material {
    return MaterialFromJSONTyped(json, false);
}

export function MaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Material {
    return json as Material;
}

export function MaterialToJSON(value?: Material | null): any {
    return value as any;
}

