/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Character,
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
} from './Character';

/**
 * 
 * @export
 * @interface NonPlayer
 */
export interface NonPlayer {
    /**
     * 
     * @type {Character}
     * @memberof NonPlayer
     */
    character: Character;
    /**
     * 
     * @type {boolean}
     * @memberof NonPlayer
     */
    can_be_looted: boolean;
    /**
     * 
     * @type {string}
     * @memberof NonPlayer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof NonPlayer
     */
    name?: string;
}

export function NonPlayerFromJSON(json: any): NonPlayer {
    return NonPlayerFromJSONTyped(json, false);
}

export function NonPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NonPlayer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'character': CharacterFromJSON(json['character']),
        'can_be_looted': json['can_be_looted'],
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function NonPlayerToJSON(value?: NonPlayer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'character': CharacterToJSON(value.character),
        'can_be_looted': value.can_be_looted,
        'id': value.id,
        'name': value.name,
    };
}

