/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GameEvent,
    GameEventFromJSON,
    GameEventFromJSONTyped,
    GameEventToJSON,
} from './GameEvent';
import {
    PerformAction,
    PerformActionFromJSON,
    PerformActionFromJSONTyped,
    PerformActionToJSON,
} from './PerformAction';

/**
 * 
 * @export
 * @interface NpcLooted
 */
export interface NpcLooted {
    /**
     * 
     * @type {Array<GameEvent>}
     * @memberof NpcLooted
     */
    events: Array<GameEvent>;
    /**
     * 
     * @type {Array<PerformAction>}
     * @memberof NpcLooted
     */
    actions: Array<PerformAction>;
}

export function NpcLootedFromJSON(json: any): NpcLooted {
    return NpcLootedFromJSONTyped(json, false);
}

export function NpcLootedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NpcLooted {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(GameEventFromJSON)),
        'actions': ((json['actions'] as Array<any>).map(PerformActionFromJSON)),
    };
}

export function NpcLootedToJSON(value?: NpcLooted | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': ((value.events as Array<any>).map(GameEventToJSON)),
        'actions': ((value.actions as Array<any>).map(PerformActionToJSON)),
    };
}

