/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Poison
 */
export interface Poison {
    /**
     * 
     * @type {number}
     * @memberof Poison
     */
    damage: number;
    /**
     * 
     * @type {number}
     * @memberof Poison
     */
    duration: number;
}

export function PoisonFromJSON(json: any): Poison {
    return PoisonFromJSONTyped(json, false);
}

export function PoisonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Poison {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'damage': json['damage'],
        'duration': json['duration'],
    };
}

export function PoisonToJSON(value?: Poison | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'damage': value.damage,
        'duration': value.duration,
    };
}

