/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Species = {
    Bugbear: 'bugbear',
    Dragonkin: 'dragonkin',
    Frogkin: 'frogkin',
    Goblin: 'goblin',
    Hobgoblin: 'hobgoblin',
    Kobold: 'kobold',
    Lizardkin: 'lizardkin',
    Moblin: 'moblin',
    Ogre: 'ogre',
    Orc: 'orc',
    Phantom: 'phantom',
    Rockoblin: 'rockoblin',
    Shadow: 'shadow',
    Turtlekin: 'turtlekin'
} as const;
export type Species = typeof Species[keyof typeof Species];


export function SpeciesFromJSON(json: any): Species {
    return SpeciesFromJSONTyped(json, false);
}

export function SpeciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Species {
    return json as Species;
}

export function SpeciesToJSON(value?: Species | null): any {
    return value as any;
}

