/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Health,
    HealthFromJSON,
    HealthFromJSONTyped,
    HealthToJSON,
} from './Health';
import {
    Size,
    SizeFromJSON,
    SizeFromJSONTyped,
    SizeToJSON,
} from './Size';

/**
 * 
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * 
     * @type {Health}
     * @memberof Stats
     */
    health?: Health;
    /**
     * 
     * @type {boolean}
     * @memberof Stats
     */
    health_known: boolean;
    /**
     * 
     * @type {Size}
     * @memberof Stats
     */
    height: Size;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'health': !exists(json, 'health') ? undefined : HealthFromJSON(json['health']),
        'health_known': json['health_known'],
        'height': SizeFromJSON(json['height']),
    };
}

export function StatsToJSON(value?: Stats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'health': HealthToJSON(value.health),
        'health_known': value.health_known,
        'height': SizeToJSON(value.height),
    };
}

