/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Tag = {
    Accessory: 'accessory',
    Armour: 'armour',
    Blade: 'blade',
    Blunt: 'blunt',
    Bone: 'bone',
    Cloth: 'cloth',
    Clothing: 'clothing',
    Combat: 'combat',
    Consumable: 'consumable',
    Container: 'container',
    Damage: 'damage',
    Defense: 'defense',
    Equipped: 'equipped',
    Fixture: 'fixture',
    Instrument: 'instrument',
    Teachable: 'teachable',
    Leather: 'leather',
    Metal: 'metal',
    Paper: 'paper',
    Rope: 'rope',
    Shield: 'shield',
    Stone: 'stone',
    Whip: 'whip',
    Wood: 'wood'
} as const;
export type Tag = typeof Tag[keyof typeof Tag];


export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    return json as Tag;
}

export function TagToJSON(value?: Tag | null): any {
    return value as any;
}

