/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ThrowableEffect,
    ThrowableEffectFromJSON,
    ThrowableEffectFromJSONTyped,
    ThrowableEffectToJSON,
} from './ThrowableEffect';

/**
 * 
 * @export
 * @interface Throwable
 */
export interface Throwable {
    /**
     * 
     * @type {number}
     * @memberof Throwable
     */
    uses: number;
    /**
     * 
     * @type {ThrowableEffect}
     * @memberof Throwable
     */
    effect: ThrowableEffect;
}

export function ThrowableFromJSON(json: any): Throwable {
    return ThrowableFromJSONTyped(json, false);
}

export function ThrowableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Throwable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uses': json['uses'],
        'effect': ThrowableEffectFromJSON(json['effect']),
    };
}

export function ThrowableToJSON(value?: Throwable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uses': value.uses,
        'effect': ThrowableEffectToJSON(value.effect),
    };
}

