/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GeneratedGame,
    GeneratedGameFromJSON,
    GeneratedGameToJSON,
} from '../models';

/**
 * GamesApi - interface
 * 
 * @export
 * @interface GamesApiInterface
 */
export interface GamesApiInterface {
    /**
     * # Example  POST `/my_username/games/generate` to generate and save a new game for my_username
     * @summary Generate and persist a new game.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApiInterface
     */
    generateGameRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GeneratedGame>>;

    /**
     * # Example  POST `/my_username/games/generate` to generate and save a new game for my_username
     * Generate and persist a new game.
     */
    generateGame(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GeneratedGame>;

    /**
     * # Example  Call `/my_username/games/ids` to retrieve all game ids for my_username
     * @summary Get IDs of all current games
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApiInterface
     */
    getGameIdsRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * # Example  Call `/my_username/games/ids` to retrieve all game ids for my_username
     * Get IDs of all current games
     */
    getGameIds(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<string>>;

}

/**
 * 
 */
export class GamesApi extends runtime.BaseAPI implements GamesApiInterface {

    /**
     * # Example  POST `/my_username/games/generate` to generate and save a new game for my_username
     * Generate and persist a new game.
     */
    async generateGameRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GeneratedGame>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["UNDERWORLD-TOKEN"] = this.configuration.apiKey("UNDERWORLD-TOKEN"); // UnderworldApiKeyAuthorization authentication
        }

        const response = await this.request({
            path: `/games/generate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratedGameFromJSON(jsonValue));
    }

    /**
     * # Example  POST `/my_username/games/generate` to generate and save a new game for my_username
     * Generate and persist a new game.
     */
    async generateGame(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GeneratedGame> {
        const response = await this.generateGameRaw(initOverrides);
        return await response.value();
    }

    /**
     * # Example  Call `/my_username/games/ids` to retrieve all game ids for my_username
     * Get IDs of all current games
     */
    async getGameIdsRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["UNDERWORLD-TOKEN"] = this.configuration.apiKey("UNDERWORLD-TOKEN"); // UnderworldApiKeyAuthorization authentication
        }

        const response = await this.request({
            path: `/games/ids`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * # Example  Call `/my_username/games/ids` to retrieve all game ids for my_username
     * Get IDs of all current games
     */
    async getGameIds(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<string>> {
        const response = await this.getGameIdsRaw(initOverrides);
        return await response.value();
    }

}
