/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AttackEffect = {
    Acidic: 'acidic',
    Crushing: 'crushing',
    Sharp: 'sharp',
    Toxic: 'toxic'
} as const;
export type AttackEffect = typeof AttackEffect[keyof typeof AttackEffect];


export function AttackEffectFromJSON(json: any): AttackEffect {
    return AttackEffectFromJSONTyped(json, false);
}

export function AttackEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttackEffect {
    return json as AttackEffect;
}

export function AttackEffectToJSON(value?: AttackEffect | null): any {
    return value as any;
}

