/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CastSpellOnPlayer
 */
export interface CastSpellOnPlayer {
    /**
     * 
     * @type {string}
     * @memberof CastSpellOnPlayer
     */
    spell_id: string;
}

export function CastSpellOnPlayerFromJSON(json: any): CastSpellOnPlayer {
    return CastSpellOnPlayerFromJSONTyped(json, false);
}

export function CastSpellOnPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CastSpellOnPlayer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spell_id': json['spell_id'],
    };
}

export function CastSpellOnPlayerToJSON(value?: CastSpellOnPlayer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spell_id': value.spell_id,
    };
}

