/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharacterKnowledge
 */
export interface CharacterKnowledge {
    /**
     * 
     * @type {boolean}
     * @memberof CharacterKnowledge
     */
    knows_health: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterKnowledge
     */
    knows_species: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterKnowledge
     */
    knows_life_modifier: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterKnowledge
     */
    knows_inventory: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterKnowledge
     */
    knows_packed_in_inventory: boolean;
}

export function CharacterKnowledgeFromJSON(json: any): CharacterKnowledge {
    return CharacterKnowledgeFromJSONTyped(json, false);
}

export function CharacterKnowledgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterKnowledge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'knows_health': json['knows_health'],
        'knows_species': json['knows_species'],
        'knows_life_modifier': json['knows_life_modifier'],
        'knows_inventory': json['knows_inventory'],
        'knows_packed_in_inventory': json['knows_packed_in_inventory'],
    };
}

export function CharacterKnowledgeToJSON(value?: CharacterKnowledge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'knows_health': value.knows_health,
        'knows_species': value.knows_species,
        'knows_life_modifier': value.knows_life_modifier,
        'knows_inventory': value.knows_inventory,
        'knows_packed_in_inventory': value.knows_packed_in_inventory,
    };
}

