/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Attack,
    AttackFromJSON,
    AttackFromJSONTyped,
    AttackToJSON,
} from './Attack';
import {
    Defense,
    DefenseFromJSON,
    DefenseFromJSONTyped,
    DefenseToJSON,
} from './Defense';

/**
 * 
 * @export
 * @interface EffectsView
 */
export interface EffectsView {
    /**
     * 
     * @type {Defense}
     * @memberof EffectsView
     */
    shield_aura?: Defense;
    /**
     * 
     * @type {boolean}
     * @memberof EffectsView
     */
    knows_has_shield_aura: boolean;
    /**
     * 
     * @type {Attack}
     * @memberof EffectsView
     */
    retribution_aura?: Attack;
    /**
     * 
     * @type {boolean}
     * @memberof EffectsView
     */
    knows_has_retribution_aura: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EffectsView
     */
    resurrection_aura: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EffectsView
     */
    knows_has_resurrection_aura: boolean;
}

export function EffectsViewFromJSON(json: any): EffectsView {
    return EffectsViewFromJSONTyped(json, false);
}

export function EffectsViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectsView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shield_aura': !exists(json, 'shield_aura') ? undefined : DefenseFromJSON(json['shield_aura']),
        'knows_has_shield_aura': json['knows_has_shield_aura'],
        'retribution_aura': !exists(json, 'retribution_aura') ? undefined : AttackFromJSON(json['retribution_aura']),
        'knows_has_retribution_aura': json['knows_has_retribution_aura'],
        'resurrection_aura': json['resurrection_aura'],
        'knows_has_resurrection_aura': json['knows_has_resurrection_aura'],
    };
}

export function EffectsViewToJSON(value?: EffectsView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shield_aura': DefenseToJSON(value.shield_aura),
        'knows_has_shield_aura': value.knows_has_shield_aura,
        'retribution_aura': AttackToJSON(value.retribution_aura),
        'knows_has_retribution_aura': value.knows_has_retribution_aura,
        'resurrection_aura': value.resurrection_aura,
        'knows_has_resurrection_aura': value.knows_has_resurrection_aura,
    };
}

