/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExitDescriptor = {
    Old: 'old',
    Rusty: 'rusty'
} as const;
export type ExitDescriptor = typeof ExitDescriptor[keyof typeof ExitDescriptor];


export function ExitDescriptorFromJSON(json: any): ExitDescriptor {
    return ExitDescriptorFromJSONTyped(json, false);
}

export function ExitDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExitDescriptor {
    return json as ExitDescriptor;
}

export function ExitDescriptorToJSON(value?: ExitDescriptor | null): any {
    return value as any;
}

