/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Item,
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface FixtureItem
 */
export interface FixtureItem {
    /**
     * 
     * @type {Item}
     * @memberof FixtureItem
     */
    item: Item;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureItem
     */
    is_hidden: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureItem
     */
    is_hidden_known: boolean;
}

export function FixtureItemFromJSON(json: any): FixtureItem {
    return FixtureItemFromJSONTyped(json, false);
}

export function FixtureItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': ItemFromJSON(json['item']),
        'is_hidden': json['is_hidden'],
        'is_hidden_known': json['is_hidden_known'],
    };
}

export function FixtureItemToJSON(value?: FixtureItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': ItemToJSON(value.item),
        'is_hidden': value.is_hidden,
        'is_hidden_known': value.is_hidden_known,
    };
}

