/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FixturePositionDescriptor = {
    IsInTheCorner: 'is_in_the_corner',
    SitsAlongOneSide: 'sits_along_one_side',
    StandsInTheCorner: 'stands_in_the_corner',
    CrackedAndBrokenOnTheGround: 'cracked_and_broken_on_the_ground'
} as const;
export type FixturePositionDescriptor = typeof FixturePositionDescriptor[keyof typeof FixturePositionDescriptor];


export function FixturePositionDescriptorFromJSON(json: any): FixturePositionDescriptor {
    return FixturePositionDescriptorFromJSONTyped(json, false);
}

export function FixturePositionDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixturePositionDescriptor {
    return json as FixturePositionDescriptor;
}

export function FixturePositionDescriptorToJSON(value?: FixturePositionDescriptor | null): any {
    return value as any;
}

