/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PerformAction,
    PerformActionFromJSON,
    PerformActionFromJSONTyped,
    PerformActionToJSON,
} from './PerformAction';

/**
 * 
 * @export
 * @interface FixtureInspected
 */
export interface FixtureInspected {
    /**
     * 
     * @type {boolean}
     * @memberof FixtureInspected
     */
    canBeOpenedDiscovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureInspected
     */
    hasHiddenDiscovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureInspected
     */
    hiddenItemsDiscovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureInspected
     */
    containedItemsDiscovered: boolean;
    /**
     * 
     * @type {Array<PerformAction>}
     * @memberof FixtureInspected
     */
    actions: Array<PerformAction>;
}

export function FixtureInspectedFromJSON(json: any): FixtureInspected {
    return FixtureInspectedFromJSONTyped(json, false);
}

export function FixtureInspectedFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureInspected {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'canBeOpenedDiscovered': json['can_be_opened_discovered'],
        'hasHiddenDiscovered': json['has_hidden_discovered'],
        'hiddenItemsDiscovered': json['hidden_items_discovered'],
        'containedItemsDiscovered': json['contained_items_discovered'],
        'actions': ((json['actions'] as Array<any>).map(PerformActionFromJSON)),
    };
}

export function FixtureInspectedToJSON(value?: FixtureInspected | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'can_be_opened_discovered': value.canBeOpenedDiscovered,
        'has_hidden_discovered': value.hasHiddenDiscovered,
        'hidden_items_discovered': value.hiddenItemsDiscovered,
        'contained_items_discovered': value.containedItemsDiscovered,
        'actions': ((value.actions as Array<any>).map(PerformActionToJSON)),
    };
}

