/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventName,
    EventNameFromJSON,
    EventNameFromJSONTyped,
    EventNameToJSON,
} from './EventName';

/**
 * 
 * @export
 * @interface GameEvent
 */
export interface GameEvent {
    /**
     * 
     * @type {EventName}
     * @memberof GameEvent
     */
    name: EventName;
    /**
     * 
     * @type {any}
     * @memberof GameEvent
     */
    data?: any | null;
}

export function GameEventFromJSON(json: any): GameEvent {
    return GameEventFromJSONTyped(json, false);
}

export function GameEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': EventNameFromJSON(json['name']),
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function GameEventToJSON(value?: GameEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': EventNameToJSON(value.name),
        'data': value.data,
    };
}

