/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PerformAction,
    PerformActionFromJSON,
    PerformActionFromJSONTyped,
    PerformActionToJSON,
} from './PerformAction';

/**
 * 
 * @export
 * @interface GeneratedGame
 */
export interface GeneratedGame {
    /**
     * 
     * @type {string}
     * @memberof GeneratedGame
     */
    gameId: string;
    /**
     * 
     * @type {Array<PerformAction>}
     * @memberof GeneratedGame
     */
    actions: Array<PerformAction>;
}

export function GeneratedGameFromJSON(json: any): GeneratedGame {
    return GeneratedGameFromJSONTyped(json, false);
}

export function GeneratedGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedGame {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameId': json['game_id'],
        'actions': ((json['actions'] as Array<any>).map(PerformActionFromJSON)),
    };
}

export function GeneratedGameToJSON(value?: GeneratedGame | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'game_id': value.gameId,
        'actions': ((value.actions as Array<any>).map(PerformActionToJSON)),
    };
}

