/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PerformAction,
    PerformActionFromJSON,
    PerformActionFromJSONTyped,
    PerformActionToJSON,
} from './PerformAction';

/**
 * 
 * @export
 * @interface GeneratedPlayerCharacter
 */
export interface GeneratedPlayerCharacter {
    /**
     * 
     * @type {Array<PerformAction>}
     * @memberof GeneratedPlayerCharacter
     */
    actions: Array<PerformAction>;
    /**
     * 
     * @type {string}
     * @memberof GeneratedPlayerCharacter
     */
    playerCharacterId: string;
    /**
     * 
     * @type {boolean}
     * @memberof GeneratedPlayerCharacter
     */
    setAsCurrent: boolean;
}

export function GeneratedPlayerCharacterFromJSON(json: any): GeneratedPlayerCharacter {
    return GeneratedPlayerCharacterFromJSONTyped(json, false);
}

export function GeneratedPlayerCharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedPlayerCharacter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actions': ((json['actions'] as Array<any>).map(PerformActionFromJSON)),
        'playerCharacterId': json['player_character_id'],
        'setAsCurrent': json['set_as_current'],
    };
}

export function GeneratedPlayerCharacterToJSON(value?: GeneratedPlayerCharacter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actions': ((value.actions as Array<any>).map(PerformActionToJSON)),
        'player_character_id': value.playerCharacterId,
        'set_as_current': value.setAsCurrent,
    };
}

