/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GroupDescriptor = {
    A: 'a',
    ALone: 'a_lone',
    ASingle: 'a_single'
} as const;
export type GroupDescriptor = typeof GroupDescriptor[keyof typeof GroupDescriptor];


export function GroupDescriptorFromJSON(json: any): GroupDescriptor {
    return GroupDescriptorFromJSONTyped(json, false);
}

export function GroupDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDescriptor {
    return json as GroupDescriptor;
}

export function GroupDescriptorToJSON(value?: GroupDescriptor | null): any {
    return value as any;
}

