/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Identifier
 */
export interface Identifier {
    /**
     * 
     * @type {string}
     * @memberof Identifier
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Identifier
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Identifier
     */
    nameKnown: boolean;
}

export function IdentifierFromJSON(json: any): Identifier {
    return IdentifierFromJSONTyped(json, false);
}

export function IdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): Identifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nameKnown': json['name_known'],
    };
}

export function IdentifierToJSON(value?: Identifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'name_known': value.nameKnown,
    };
}

