/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Attack,
    AttackFromJSON,
    AttackFromJSONTyped,
    AttackToJSON,
} from './Attack';
import {
    Consumable,
    ConsumableFromJSON,
    ConsumableFromJSONTyped,
    ConsumableToJSON,
} from './Consumable';
import {
    Defense,
    DefenseFromJSON,
    DefenseFromJSONTyped,
    DefenseToJSON,
} from './Defense';
import {
    ItemDescriptor,
    ItemDescriptorFromJSON,
    ItemDescriptorFromJSONTyped,
    ItemDescriptorToJSON,
} from './ItemDescriptor';
import {
    ItemType,
    ItemTypeFromJSON,
    ItemTypeFromJSONTyped,
    ItemTypeToJSON,
} from './ItemType';
import {
    Material,
    MaterialFromJSON,
    MaterialFromJSONTyped,
    MaterialToJSON,
} from './Material';
import {
    Tag,
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    name?: string;
    /**
     * 
     * @type {ItemType}
     * @memberof Item
     */
    item_type: ItemType;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof Item
     */
    tags: Array<Tag>;
    /**
     * 
     * @type {Array<ItemDescriptor>}
     * @memberof Item
     */
    descriptors: Array<ItemDescriptor>;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    descriptors_known: boolean;
    /**
     * 
     * @type {Material}
     * @memberof Item
     */
    material?: Material;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    material_known: boolean;
    /**
     * 
     * @type {Attack}
     * @memberof Item
     */
    attack?: Attack;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    attack_known: boolean;
    /**
     * 
     * @type {Defense}
     * @memberof Item
     */
    defense?: Defense;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    defense_known: boolean;
    /**
     * 
     * @type {Consumable}
     * @memberof Item
     */
    consumable?: Consumable;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    knows_consumable: boolean;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'item_type': ItemTypeFromJSON(json['item_type']),
        'tags': ((json['tags'] as Array<any>).map(TagFromJSON)),
        'descriptors': ((json['descriptors'] as Array<any>).map(ItemDescriptorFromJSON)),
        'descriptors_known': json['descriptors_known'],
        'material': !exists(json, 'material') ? undefined : MaterialFromJSON(json['material']),
        'material_known': json['material_known'],
        'attack': !exists(json, 'attack') ? undefined : AttackFromJSON(json['attack']),
        'attack_known': json['attack_known'],
        'defense': !exists(json, 'defense') ? undefined : DefenseFromJSON(json['defense']),
        'defense_known': json['defense_known'],
        'consumable': !exists(json, 'consumable') ? undefined : ConsumableFromJSON(json['consumable']),
        'knows_consumable': json['knows_consumable'],
    };
}

export function ItemToJSON(value?: Item | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'item_type': ItemTypeToJSON(value.item_type),
        'tags': ((value.tags as Array<any>).map(TagToJSON)),
        'descriptors': ((value.descriptors as Array<any>).map(ItemDescriptorToJSON)),
        'descriptors_known': value.descriptors_known,
        'material': MaterialToJSON(value.material),
        'material_known': value.material_known,
        'attack': AttackToJSON(value.attack),
        'attack_known': value.attack_known,
        'defense': DefenseToJSON(value.defense),
        'defense_known': value.defense_known,
        'consumable': ConsumableToJSON(value.consumable),
        'knows_consumable': value.knows_consumable,
    };
}

