/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ItemType = {
    Breastplate: 'breastplate',
    Boots: 'boots',
    BowlerHat: 'bowler_hat',
    Buckler: 'buckler',
    Cloak: 'cloak',
    Club: 'club',
    Crown: 'crown',
    Dagger: 'dagger',
    Dirk: 'dirk',
    Fedora: 'fedora',
    Gloves: 'gloves',
    GreatSword: 'great_sword',
    Halberd: 'halberd',
    Hammer: 'hammer',
    Helm: 'helm',
    LoinCloth: 'loin_cloth',
    LongSword: 'long_sword',
    Mace: 'mace',
    Mask: 'mask',
    Morningstar: 'morningstar',
    Pike: 'pike',
    PlateBoots: 'plate_boots',
    PlateGauntlets: 'plate_gauntlets',
    PlateHelmet: 'plate_helmet',
    Scroll: 'scroll',
    Shield: 'shield',
    ShortSword: 'short_sword',
    Shirt: 'shirt',
    Shackles: 'shackles',
    Spear: 'spear',
    TopHat: 'top_hat',
    Trousers: 'trousers',
    Vest: 'vest',
    Whip: 'whip'
} as const;
export type ItemType = typeof ItemType[keyof typeof ItemType];


export function ItemTypeFromJSON(json: any): ItemType {
    return ItemTypeFromJSONTyped(json, false);
}

export function ItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemType {
    return json as ItemType;
}

export function ItemTypeToJSON(value?: ItemType | null): any {
    return value as any;
}

