/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LifeModifier = {
    Skeleton: 'skeleton',
    Vampire: 'vampire',
    Zombie: 'zombie'
} as const;
export type LifeModifier = typeof LifeModifier[keyof typeof LifeModifier];


export function LifeModifierFromJSON(json: any): LifeModifier {
    return LifeModifierFromJSONTyped(json, false);
}

export function LifeModifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): LifeModifier {
    return json as LifeModifier;
}

export function LifeModifierToJSON(value?: LifeModifier | null): any {
    return value as any;
}

