/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PerformAction,
    PerformActionFromJSON,
    PerformActionFromJSONTyped,
    PerformActionToJSON,
} from './PerformAction';

/**
 * 
 * @export
 * @interface NpcInspected
 */
export interface NpcInspected {
    /**
     * 
     * @type {boolean}
     * @memberof NpcInspected
     */
    healthDiscovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NpcInspected
     */
    nameDiscovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NpcInspected
     */
    packedItemsDiscovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NpcInspected
     */
    hiddenItemsDiscovered: boolean;
    /**
     * 
     * @type {Array<PerformAction>}
     * @memberof NpcInspected
     */
    actions: Array<PerformAction>;
}

export function NpcInspectedFromJSON(json: any): NpcInspected {
    return NpcInspectedFromJSONTyped(json, false);
}

export function NpcInspectedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NpcInspected {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'healthDiscovered': json['health_discovered'],
        'nameDiscovered': json['name_discovered'],
        'packedItemsDiscovered': json['packed_items_discovered'],
        'hiddenItemsDiscovered': json['hidden_items_discovered'],
        'actions': ((json['actions'] as Array<any>).map(PerformActionFromJSON)),
    };
}

export function NpcInspectedToJSON(value?: NpcInspected | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'health_discovered': value.healthDiscovered,
        'name_discovered': value.nameDiscovered,
        'packed_items_discovered': value.packedItemsDiscovered,
        'hidden_items_discovered': value.hiddenItemsDiscovered,
        'actions': ((value.actions as Array<any>).map(PerformActionToJSON)),
    };
}

