/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NpcPositionDescriptor = {
    IsGlaringAtYou: 'is_glaring_at_you',
    IsGlaringAtYouFromNearby: 'is_glaring_at_you_from_nearby',
    InCornerStands: 'in_corner_stands',
    IsStandingAround: 'is_standing_around',
    IsLeaningAgainstTheTable: 'is_leaning_against_the_table',
    StandsOnTheTable: 'stands_on_the_table',
    IsStandingOnTheTable: 'is_standing_on_the_table',
    IsSittingInAChair: 'is_sitting_in_a_chair',
    IsStandingInABarrel: 'is_standing_in_a_barrel',
    IsSleepingInTheBed: 'is_sleeping_in_the_bed',
    IsSleepingInACot: 'is_sleeping_in_a_cot',
    IsSleepingInSleepingRoll: 'is_sleeping_in_sleeping_roll',
    IsLeaningOnACrate: 'is_leaning_on_a_crate',
    IsLookingAtTheWeaponRack: 'is_looking_at_the_weapon_rack',
    IsCrouchedOverChest: 'is_crouched_over_chest',
    IsRummagingThroughAChest: 'is_rummaging_through_a_chest',
    IsCrouchedInTheCenterOfRoom: 'is_crouched_in_the_center_of_room',
    IsSittingAndDozingInCenterOfRoom: 'is_sitting_and_dozing_in_center_of_room',
    SittingInAChairIs: 'sitting_in_a_chair_is',
    IsLyingInPoolBlood: 'is_lying_in_pool_blood'
} as const;
export type NpcPositionDescriptor = typeof NpcPositionDescriptor[keyof typeof NpcPositionDescriptor];


export function NpcPositionDescriptorFromJSON(json: any): NpcPositionDescriptor {
    return NpcPositionDescriptorFromJSONTyped(json, false);
}

export function NpcPositionDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): NpcPositionDescriptor {
    return json as NpcPositionDescriptor;
}

export function NpcPositionDescriptorToJSON(value?: NpcPositionDescriptor | null): any {
    return value as any;
}

