/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GroupDescriptor,
    GroupDescriptorFromJSON,
    GroupDescriptorFromJSONTyped,
    GroupDescriptorToJSON,
} from './GroupDescriptor';
import {
    NonPlayer,
    NonPlayerFromJSON,
    NonPlayerFromJSONTyped,
    NonPlayerToJSON,
} from './NonPlayer';
import {
    NpcPositionDescriptor,
    NpcPositionDescriptorFromJSON,
    NpcPositionDescriptorFromJSONTyped,
    NpcPositionDescriptorToJSON,
} from './NpcPositionDescriptor';

/**
 * 
 * @export
 * @interface NpcPosition
 */
export interface NpcPosition {
    /**
     * 
     * @type {GroupDescriptor}
     * @memberof NpcPosition
     */
    groupDescriptor?: GroupDescriptor;
    /**
     * 
     * @type {NonPlayer}
     * @memberof NpcPosition
     */
    npc: NonPlayer;
    /**
     * 
     * @type {NpcPositionDescriptor}
     * @memberof NpcPosition
     */
    positionDescriptor?: NpcPositionDescriptor;
}

export function NpcPositionFromJSON(json: any): NpcPosition {
    return NpcPositionFromJSONTyped(json, false);
}

export function NpcPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NpcPosition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupDescriptor': !exists(json, 'group_descriptor') ? undefined : GroupDescriptorFromJSON(json['group_descriptor']),
        'npc': NonPlayerFromJSON(json['npc']),
        'positionDescriptor': !exists(json, 'position_descriptor') ? undefined : NpcPositionDescriptorFromJSON(json['position_descriptor']),
    };
}

export function NpcPositionToJSON(value?: NpcPosition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group_descriptor': GroupDescriptorToJSON(value.groupDescriptor),
        'npc': NonPlayerToJSON(value.npc),
        'position_descriptor': NpcPositionDescriptorToJSON(value.positionDescriptor),
    };
}

