/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OilSplashEffect
 */
export interface OilSplashEffect {
    /**
     * 
     * @type {boolean}
     * @memberof OilSplashEffect
     */
    covers_all_enemies: boolean;
}

export function OilSplashEffectFromJSON(json: any): OilSplashEffect {
    return OilSplashEffectFromJSONTyped(json, false);
}

export function OilSplashEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): OilSplashEffect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'covers_all_enemies': json['covers_all_enemies'],
    };
}

export function OilSplashEffectToJSON(value?: OilSplashEffect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'covers_all_enemies': value.covers_all_enemies,
    };
}

