/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenFixtureHiddenCompartment
 */
export interface OpenFixtureHiddenCompartment {
    /**
     * 
     * @type {string}
     * @memberof OpenFixtureHiddenCompartment
     */
    fixture_id: string;
}

export function OpenFixtureHiddenCompartmentFromJSON(json: any): OpenFixtureHiddenCompartment {
    return OpenFixtureHiddenCompartmentFromJSONTyped(json, false);
}

export function OpenFixtureHiddenCompartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenFixtureHiddenCompartment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fixture_id': json['fixture_id'],
    };
}

export function OpenFixtureHiddenCompartmentToJSON(value?: OpenFixtureHiddenCompartment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fixture_id': value.fixture_id,
    };
}

