/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThrowItemAtNpc
 */
export interface ThrowItemAtNpc {
    /**
     * 
     * @type {string}
     * @memberof ThrowItemAtNpc
     */
    npc_id: string;
    /**
     * 
     * @type {string}
     * @memberof ThrowItemAtNpc
     */
    item_id: string;
}

export function ThrowItemAtNpcFromJSON(json: any): ThrowItemAtNpc {
    return ThrowItemAtNpcFromJSONTyped(json, false);
}

export function ThrowItemAtNpcFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThrowItemAtNpc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'npc_id': json['npc_id'],
        'item_id': json['item_id'],
    };
}

export function ThrowItemAtNpcToJSON(value?: ThrowItemAtNpc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'npc_id': value.npc_id,
        'item_id': value.item_id,
    };
}

