[package]
name = "underworld_web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "1a9567fc6d91c3c611fa9a9e4f4451a4df2d1ad4" }
getrandom = {version = "0.2.4", features= ["js"] }
