[package]
name = "underworld_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "c8207b11066599c78745ea3027807bb61e9756a3", features = ["serialization", "openapi"] }
# underworld_core = { path = "../underworld_core", features = ["serialization", "openapi"] }
serde_json = { version = "1.0.81" }
rand = "0.8.5"
redis = { version = "0.21.5", features = ["tokio-comp"] }
poem = { version = "1.3.29", features = ["static-files"] }
poem-openapi = { version = "1.3.29", features = ["swagger-ui"]}
tokio = { version = "1.18.1", features = ["rt-multi-thread"] }
