[package]
name = "underworld_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
bevy_ecs = { version = "0.6.0", optional = true }
serde = { version = "1.0.133", features = ["derive"], optional = true }
serde_json = { version = "1.0.75", optional = true }
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng", "serde"] }

[features]
bevy_components = ["bevy_ecs"]
serialization = ["serde"]
json = [ "serde_json" ]
