[package]
name = "underworld_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "e6fe7918b90559cabc7ae3e240291076582c1840", features = ["serialization", "openapi"] }
serde_json = { version = "1.0.81" }
rand = "0.8.5"
poem = { version = "1.3.30", features = ["static-files"] }
poem-openapi = { version = "2.0.0", features = ["swagger-ui"]}
tokio = { version = "1.19.1", features = ["rt-multi-thread"] }
sqlx = { version = "0.5.13", features = [ "runtime-tokio-native-tls" , "postgres" ] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.31"
