[package]
name = "underworld_web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "c818ffd7170ae81b4a39333960ab77d745a089bc" }
getrandom = {version = "0.2.6", features= ["js"] }
rand = "0.8.5"
