[package]
name = "underworld_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "40765dfc8160a39b3f754377fe412da926de70d0", features = ["serialization", "openapi"] }
serde_json = { version = "1.0.78" }
rand = "0.8.5"
redis = { version = "0.21.5", features = ["tokio-comp"] }
poem = { version = "1.3.5", features = ["static-files"] }
poem-openapi = { version = "1.3.5", features = ["swagger-ui"]}
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
