[package]
name = "underworld_core"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bevy_ecs = { version = "0.7.0", optional = true }
enum-iterator = "0.7.0"
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
uuid = { version = "1.0.0", features = ["v4", "fast-rng", "serde"] }
poem-openapi = { version = "1.3.29", optional = true }

[features]
bevy_components = ["bevy_ecs"]
serialization = ["serde"]
json = [ "serde_json" ]
openapi = ["poem-openapi"]
