[package]
name = "underworld_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes"] }
serde = { version = "1.0.135", features = ["derive"] }
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "8ee2ca2b7214a7a9dbe03c850dc00a9ca55e70ef", features = ["serialization"] }
serde_json = { version = "1.0.78" }
