[package]
name = "underworld_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
underworld_core = { git = "https://github.com/derrickp/underworld_core", rev = "6b2e4238da62f57dc12cfd601f95bb4eb959c5ab", features = ["serialization", "openapi"] }
# underworld_core = { path = "../underworld_core", features = ["serialization", "openapi"] }
serde_json = { version = "1.0.81" }
rand = "0.8.5"
poem = { version = "1.3.30", features = ["static-files"] }
poem-openapi = { version = "1.3.30", features = ["swagger-ui"]}
tokio = { version = "1.18.2", features = ["rt-multi-thread"] }
sqlx = { version = "0.5.13", features = [ "runtime-tokio-native-tls" , "postgres" ] }
