version: '3'

name: underworld_server

services:
  database:
    image: postgres:14.5
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'underworld_server'

  web:
    build: .
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://postgres:postgres@database/underworld_server"
      FROM_EMAIL: $FROM_EMAIL
      FRONTEND_URL: $FRONTEND_URL
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      SENDGRID_TEMPLATE_ID: $SENDGRID_TEMPLATE_ID

networks:
  mynetwork:
