# fly.toml file generated for underworldserver on 2022-08-27T11:26:56-07:00

app = "underworldserver"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FROM_EMAIL="email@spinninggoblin.com"
  FRONTEND_URL="https://www.spinninggoblin.com/underworld"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
