/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttackNpc
 */
export interface AttackNpc {
    /**
     * 
     * @type {string}
     * @memberof AttackNpc
     */
    npc_id: string;
}

export function AttackNpcFromJSON(json: any): AttackNpc {
    return AttackNpcFromJSONTyped(json, false);
}

export function AttackNpcFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttackNpc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'npc_id': json['npc_id'],
    };
}

export function AttackNpcToJSON(value?: AttackNpc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'npc_id': value.npc_id,
    };
}

