/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CastSpellOnNpc
 */
export interface CastSpellOnNpc {
    /**
     * 
     * @type {string}
     * @memberof CastSpellOnNpc
     */
    npc_id: string;
    /**
     * 
     * @type {string}
     * @memberof CastSpellOnNpc
     */
    spell_id: string;
}

export function CastSpellOnNpcFromJSON(json: any): CastSpellOnNpc {
    return CastSpellOnNpcFromJSONTyped(json, false);
}

export function CastSpellOnNpcFromJSONTyped(json: any, ignoreDiscriminator: boolean): CastSpellOnNpc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'npc_id': json['npc_id'],
        'spell_id': json['spell_id'],
    };
}

export function CastSpellOnNpcToJSON(value?: CastSpellOnNpc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'npc_id': value.npc_id,
        'spell_id': value.spell_id,
    };
}

