/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExitMap
 */
export interface ExitMap {
    /**
     * 
     * @type {string}
     * @memberof ExitMap
     */
    exit_id: string;
    /**
     * 
     * @type {string}
     * @memberof ExitMap
     */
    left_room_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExitMap
     */
    right_room_id?: string;
}

export function ExitMapFromJSON(json: any): ExitMap {
    return ExitMapFromJSONTyped(json, false);
}

export function ExitMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExitMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exit_id': json['exit_id'],
        'left_room_id': !exists(json, 'left_room_id') ? undefined : json['left_room_id'],
        'right_room_id': !exists(json, 'right_room_id') ? undefined : json['right_room_id'],
    };
}

export function ExitMapToJSON(value?: ExitMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exit_id': value.exit_id,
        'left_room_id': value.left_room_id,
        'right_room_id': value.right_room_id,
    };
}

