/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Item,
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface FixtureItem
 */
export interface FixtureItem {
    /**
     * 
     * @type {Item}
     * @memberof FixtureItem
     */
    item: Item;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureItem
     */
    is_inside: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureItem
     */
    is_in_hidden_compartment?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureItem
     */
    is_in_hidden_compartment_known: boolean;
}

export function FixtureItemFromJSON(json: any): FixtureItem {
    return FixtureItemFromJSONTyped(json, false);
}

export function FixtureItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': ItemFromJSON(json['item']),
        'is_inside': json['is_inside'],
        'is_in_hidden_compartment': !exists(json, 'is_in_hidden_compartment') ? undefined : json['is_in_hidden_compartment'],
        'is_in_hidden_compartment_known': json['is_in_hidden_compartment_known'],
    };
}

export function FixtureItemToJSON(value?: FixtureItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': ItemToJSON(value.item),
        'is_inside': value.is_inside,
        'is_in_hidden_compartment': value.is_in_hidden_compartment,
        'is_in_hidden_compartment_known': value.is_in_hidden_compartment_known,
    };
}

