/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FixtureKnowledge
 */
export interface FixtureKnowledge {
    /**
     * 
     * @type {boolean}
     * @memberof FixtureKnowledge
     */
    knows_has_hidden_compartment: boolean;
}

export function FixtureKnowledgeFromJSON(json: any): FixtureKnowledge {
    return FixtureKnowledgeFromJSONTyped(json, false);
}

export function FixtureKnowledgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureKnowledge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'knows_has_hidden_compartment': json['knows_has_hidden_compartment'],
    };
}

export function FixtureKnowledgeToJSON(value?: FixtureKnowledge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'knows_has_hidden_compartment': value.knows_has_hidden_compartment,
    };
}

