/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Size,
    SizeFromJSON,
    SizeFromJSONTyped,
    SizeToJSON,
} from './Size';
import {
    Species,
    SpeciesFromJSON,
    SpeciesFromJSONTyped,
    SpeciesToJSON,
} from './Species';

/**
 * 
 * @export
 * @interface GeneratePlayerCharacter
 */
export interface GeneratePlayerCharacter {
    /**
     * 
     * @type {Size}
     * @memberof GeneratePlayerCharacter
     */
    character_size?: Size;
    /**
     * 
     * @type {Species}
     * @memberof GeneratePlayerCharacter
     */
    character_species?: Species;
    /**
     * 
     * @type {string}
     * @memberof GeneratePlayerCharacter
     */
    character_name?: string;
}

export function GeneratePlayerCharacterFromJSON(json: any): GeneratePlayerCharacter {
    return GeneratePlayerCharacterFromJSONTyped(json, false);
}

export function GeneratePlayerCharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePlayerCharacter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'character_size': !exists(json, 'character_size') ? undefined : SizeFromJSON(json['character_size']),
        'character_species': !exists(json, 'character_species') ? undefined : SpeciesFromJSON(json['character_species']),
        'character_name': !exists(json, 'character_name') ? undefined : json['character_name'],
    };
}

export function GeneratePlayerCharacterToJSON(value?: GeneratePlayerCharacter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'character_size': SizeToJSON(value.character_size),
        'character_species': SpeciesToJSON(value.character_species),
        'character_name': value.character_name,
    };
}

