/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Room,
    RoomFromJSON,
    RoomFromJSONTyped,
    RoomToJSON,
} from './Room';

/**
 * 
 * @export
 * @interface GeneratedRooms
 */
export interface GeneratedRooms {
    /**
     * 
     * @type {Array<Room>}
     * @memberof GeneratedRooms
     */
    rooms: Array<Room>;
}

export function GeneratedRoomsFromJSON(json: any): GeneratedRooms {
    return GeneratedRoomsFromJSONTyped(json, false);
}

export function GeneratedRoomsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedRooms {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rooms': ((json['rooms'] as Array<any>).map(RoomFromJSON)),
    };
}

export function GeneratedRoomsToJSON(value?: GeneratedRooms | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rooms': ((value.rooms as Array<any>).map(RoomToJSON)),
    };
}

