/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Dimensions,
    DimensionsFromJSON,
    DimensionsFromJSONTyped,
    DimensionsToJSON,
} from './Dimensions';
import {
    Size,
    SizeFromJSON,
    SizeFromJSONTyped,
    SizeToJSON,
} from './Size';

/**
 * 
 * @export
 * @interface GenerateSingleRoomDimensions
 */
export interface GenerateSingleRoomDimensions {
    /**
     * 
     * @type {Size}
     * @memberof GenerateSingleRoomDimensions
     */
    height: Size;
    /**
     * 
     * @type {Size}
     * @memberof GenerateSingleRoomDimensions
     */
    width: Size;
    /**
     * 
     * @type {Size}
     * @memberof GenerateSingleRoomDimensions
     */
    length: Size;
}

export function GenerateSingleRoomDimensionsFromJSON(json: any): GenerateSingleRoomDimensions {
    return GenerateSingleRoomDimensionsFromJSONTyped(json, false);
}

export function GenerateSingleRoomDimensionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateSingleRoomDimensions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'height': SizeFromJSON(json['height']),
        'width': SizeFromJSON(json['width']),
        'length': SizeFromJSON(json['length']),
    };
}

export function GenerateSingleRoomDimensionsToJSON(value?: GenerateSingleRoomDimensions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'height': SizeToJSON(value.height),
        'width': SizeToJSON(value.width),
        'length': SizeToJSON(value.length),
    };
}

