/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An inclusive range of integers.
 * @export
 * @interface InclusiveRange
 */
export interface InclusiveRange {
    /**
     * 
     * @type {number}
     * @memberof InclusiveRange
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof InclusiveRange
     */
    max_inclusive: number;
}

export function InclusiveRangeFromJSON(json: any): InclusiveRange {
    return InclusiveRangeFromJSONTyped(json, false);
}

export function InclusiveRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InclusiveRange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'min': json['min'],
        'max_inclusive': json['max_inclusive'],
    };
}

export function InclusiveRangeToJSON(value?: InclusiveRange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'min': value.min,
        'max_inclusive': value.max_inclusive,
    };
}

