/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenFixture
 */
export interface OpenFixture {
    /**
     * 
     * @type {string}
     * @memberof OpenFixture
     */
    fixture_id: string;
}

export function OpenFixtureFromJSON(json: any): OpenFixture {
    return OpenFixtureFromJSONTyped(json, false);
}

export function OpenFixtureFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenFixture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fixture_id': json['fixture_id'],
    };
}

export function OpenFixtureToJSON(value?: OpenFixture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fixture_id': value.fixture_id,
    };
}

