/* tslint:disable */
/* eslint-disable */
/**
 * Underworld
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Statistics
 */
export interface Statistics {
    /**
     * 
     * @type {number}
     * @memberof Statistics
     */
    num_killed: number;
    /**
     * 
     * @type {number}
     * @memberof Statistics
     */
    total_damage_taken: number;
    /**
     * 
     * @type {number}
     * @memberof Statistics
     */
    total_damage_done: number;
}

export function StatisticsFromJSON(json: any): Statistics {
    return StatisticsFromJSONTyped(json, false);
}

export function StatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'num_killed': json['num_killed'],
        'total_damage_taken': json['total_damage_taken'],
        'total_damage_done': json['total_damage_done'],
    };
}

export function StatisticsToJSON(value?: Statistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'num_killed': value.num_killed,
        'total_damage_taken': value.total_damage_taken,
        'total_damage_done': value.total_damage_done,
    };
}

